name: Frontend CI/CD
on:
  push:
    branches: [dev]
    paths:
      - "frontend/**"
  pull_request:
    branches: [dev]
    paths:
      - "frontend/**"
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: kodecamp5-FE

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log In To Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME}}:${{ github.sha }}
